# Computation

<br>

***

## Introduction to Computation

***

In this notebook I am going to explore some computational problems. The topics I am going to discuss are:
<ol>
  <li>Matrix Multiplication</li>
  <li>Growth Rates (Polynomial vs Exponential)</li>
  <li>Big O Notation</li>
  <li>Turing Machines</li>
  <li>Exercise</li>
</ol>

***

## Matrix Multiplication

***

Matrix multiplication is the process of taking two matrices and multiplying them together to get one matrix. This is done by multiplying the rows of one matrix to the columns of the other. There are a number of ways to do this in Python, we are going to look at using for loops and the Numpy package in order to do so.

For Loop Multiplication:
- Using for loops for this operation is the simplest method but also can be not very practical if we were using a larger data set as inputs.
- The nested for loops calculate the result by iterating through each row and column of the matrices  and summing the results.

In [1]:
# Create two matrices 3x3 for multiplying
matrix0 = [[6, 8, 2],
           [5, 2, 7],
           [9, 12, 3]]
matrix1 = [[10, 4, 7], 
           [1, 9, 9], 
           [2, 5, 6]]

result = [[0 for x in range(3)] for y in range(3)]

# setup nested for loops for multiplying
for i in range(len(matrix0)): 
    for j in range(len(matrix1[0])): 
        for k in range(len(matrix1)):

            # Multiply the matrices together to get result
            result[i][j] += matrix0[i][k] * matrix1[k][j]

# Output the result
print(result)

[[72, 106, 126], [66, 73, 95], [108, 159, 189]]


Numpy Multiplication:
- In this part I will demonstrate how the Numpy package can be utilised for matrix multiplication.
- Numpy refers to multiplication as vectorization, it works by removing the need for the nested for loops which in turn speeds up the computation time of the program.
- This package is more  suitable for larger data sets as it is much faster than the normal nested for loops.
- There are two ways to get the result using Numpy as of Python 3.5, the first way is using the dot() method and the second is using the @ operator.

In [5]:
# Import numpy package 
import numpy as np

# setup two matrices
matrix0 = ([10, 3, 9],[2 ,14, 7],[1, 2, 5])
matrix1 = ([4, 1, 7],[6, 9, 2],[3, 8, 5])

# first result to test the dot() method
result1 = np.dot(matrix0, matrix1)

# second result to test the @ operator 
# result2 = matrix0 @ matrix1 # doesn't seem to be supported 

# output both matrices
print(result1)
# print(result2)

[[ 85 109 121]
 [113 184  77]
 [ 31  59  36]]


 Ref - https://www.geeksforgeeks.org/multiplication-two-matrices-single-line-using-numpy-python/?ref=lbp

Papers and Articles on Matrix Multiplication

Many computational problems that we often look at are not fully resolved yet.
When it comes to the matrix multiplication algorithms we are not even sure if it is computing as fast as is possible.
See the following articles and papers for some insight on this topic:
- Matrix Multiplication Inches Closer to Mythic Goal; Kevin Hartnett; Quanta magazine
- Discovering faster matrix multiplication algorithms with reinforcement learning; Alhussein Fawzi, Matej Balog, Aja Huang, Thomas Hubert, Bernardino Romera-Paredes, Mohammadamin Barekatain, Alexander Novikov, Francisco J. R. Ruiz, Julian Schrittwieser, Grzegorz Swirszcz, David Silver, Demis Hassabis & Pushmeet Kohli; Nature
- The FBHHRBNRSSSHK-Algorithm for Multiplication in Z25×5 is still not the end of the story; Manuel Kauers, Jakob Moosbauer; arXiv
- A Refined Laser Method and Faster Matrix Multiplication; Josh Alman, Virginia Vassilevska Williams; arXiv

https://github.com/ianmcloughlin/2223-S1-emerging-technologies/blob/main/notebooks/03-computation.ipynb

***

## Growth Rates (Polynomial vs Exponential)

***

***

## Big O Notation

***

***

## Turing Machines

***

***

## Exercise

***